services:
  blender:
    build: .
    volumes:
      - ./workspace:/workspace
    ports:
      - "8765:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
